CFLAGS:=-O0 # -g = debug, -O2 for optimized code CPPFLAGS for g++
CC:=g++

val01:
	$(CC) $(CFLAGS)  -o val_test01_solved val_test01_solved.cpp

val02:
	$(CC) $(CFLAGS)  -o val_test02_solved val_test02_solved.cpp

clean:
	rm -f val_test01_solved val_test02_solved *.o
